<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="WorkSheet" type="WorkSheetType" />
  <xs:element name="Worksheet" type="WorkSheetType" />

  <xs:complexType name="WorkSheetType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" minOccurs="0" />
      <xs:element name="Variables" type="VariablesType" minOccurs="0" />
      <xs:element name="Cells" type="CellsType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="VariablesType">
    <xs:sequence>
      <xs:element name="Variable" type="VariableType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="VariableType">
    <xs:sequence>
      <xs:element name="Key" type="xs:string" minOccurs="0" />
      <xs:element name="Value" type="xs:string" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="Key" type="xs:string" use="optional" />
    <xs:attribute name="Value" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:complexType name="CellsType">
    <xs:sequence>
      <xs:element name="WorkCell" type="WorkCellType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="WorkCellType">
    <xs:sequence>
      <xs:element name="Id" type="xs:int" minOccurs="0" />
      <xs:element name="Name" type="xs:string" minOccurs="0" />
      <xs:element name="Formula" type="xs:string" minOccurs="0" />
      <xs:element name="Comments" type="xs:string" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="Id" type="xs:int" use="optional" />
    <xs:attribute name="Name" type="xs:string" use="optional" />
    <xs:attribute name="Formula" type="xs:string" use="optional" />
    <xs:attribute name="Comments" type="xs:string" use="optional" />
  </xs:complexType>

</xs:schema>
